### ISSUE TITLE
190 unknown error is not returned by API

### ISSUE THREAD

**Issue by snthibaud** [OpenWonderLabs/.github#2]
### Analysis

When sending IR commands to an air conditioner through a mini Hub, the app sometimes shows 190 unknown error, but the API returns no errors at all.
The command actually failed, but there is no way to see that through the API, so I cannot retry on failure.

### Expected Behavior

API should return 190 unknown error as well.

### Steps To Reproduce

Send many commands through an IR mini hub and wait until 190 unknown error happens (it happens sporadically).

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

OS: Debian Linux
Software: Python app
Node: -
npm: -

### Additional Context

-

**Comment by snthibaud** [comment]
Why was this one closed?

**Comment by donavanbecker** [comment]
This has nothing to do with the GitHub workflow.
